# Generated by Django 5.1.3 on 2024-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.TextField(),
        ),
    ]
